# Start at 1
set -g base-index 1
setw -g pane-base-index 1

# Binds
unbind r
bind r source-file ~/.config/tmux/tmux.conf
set -g prefix C-s
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin "janoamaral/tokyo-night-tmux"
# set -g @plugin 'erikw/tmux-powerline'
# set -g @plugin 'dracula/tmux'

# Tmux-navegator
set -g @vim_navigator_mapping_left "M-h"
set -g @vim_navigator_mapping_right "M-l"
set -g @vim_navigator_mapping_up "M-k"
set -g @vim_navigator_mapping_down "M-j"

# Bar
# set -g @dracula-show-powerline true
# set -g @dracula-show-flags true
# set -g @dracula-show-left-icon session
# set -g @dracula-plugins "ssh-session cwd time"
# set -g @dracula-show-ssh-only-when-connected false
# set -g @dracula-show-ssh-session-port true
# set -g @dracula-time-format "%F %R"

# Options
set-option -sa terminal-overrides ",xterm-256color:Tc"
set -g mouse on
set -g focus-events on
set -g @bg "#16161e"
set -g @fg "#a8b0d5"
set -g @c1 "#7dcefe"
set -g @c2 "#7aa2f7"
set -g @c3 "#292e42"
set -g @c4 "#3b4261"

set -g status-style "bg=#{@bg},fg=#{@fg}"
set -g status-left-length 99
set -g status-right-length 99
set -g status-justify absolute-centre
set -g status-position top
set -g status-left '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-right '#[bg=#{@c3}] #{user}@#{host} #[bg=#{@c4}] %H:%M #[bg=#{@c2},fg=#{@bg}] #S '
set -g window-status-format "#[bg=#{@c3}] #W "
set -g window-status-current-format "#[bg=#{@c2},fg=#{@bg}] #W "


run-shell ~/.config/tmux/plugins/tmux-yank/yank.tmux
run '~/.tmux/plugins/tpm/tpm'
