backend = "glx";
vsync = true;

# Disable everything extra
shadow = false;
fading = false;

blur-method = "none";
blur-background = false;

# No animations/effects
animations = false;

# Important for stability / tearing fix
unredir-if-possible = false;
